### ISSUE TITLE
istallazione del sistema

### ISSUE THREAD

**Issue by marte-git** [ICON39/samuele.dimario.PHP-MySQL#2]
servirebbe un file di istallazione, come descritto nel testo del compito.

Poi direi che potrebbe adottare questa strategia

- un file di dati del sistema, le variabili principali da usare per l'istallazione e la connessione al dbms
- un file install.php, che include i dati del primo file (require_once), si connette al dbms, crea e popola inizialmente la base di dati (non lweb please, troppo generico) e al termine rinvia alla homepage del sistema per la login
- un file connessione.php (non index ... index e` un'altra cosa ;) in cui si include il primo file e si esegue la connessione al db. Questo file e` quello che viene incluso in tutti gi script che devono usare la base di dati (e quindi connetetrsi)

In questo modo, almeno per l'aspetto della connessione, si ottiene un sitema con buone caratteristiche di modularita`

**Comment by ICON39** [comment]
Sono state implementate le nuove modifiche sia su github che nel file zip inviato su classroom
